### ISSUE TITLE
Trading days

### ISSUE THREAD

**Issue by dguariniello** [alexkowa/x12#9]
Congratulations for your job, it is wonderful to be able to combine these two powerful tools.
I have some problems when i try to use the trading days spc, When I use it from de GUI i have no problems but when I save the parameter from the GUI and try to use it in the x12() function it doesnt work. Also I try to use de Trading days spc at the same time with the ramp (outlier)  spc but it seems that it isn't possible. On the other hand it would be great if you could include the composite spc.

**Comment by alexkowa** [comment]
Ramp outlier are not really tested yet. Composite spc would be a good addition, however due to time constraints not possible right now. 

Can you send example code of the problems you run into?

**Comment by alexkowa** [comment]
no running example provided
